# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 11:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='\u0434\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f (UTC) \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u0434\u0430\u043d\u043d\u044b\u0445 \u043e MODIS')),
                ('confidence', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='\u0434\u043e\u0441\u0442\u043e\u0432\u0435\u0440\u043d\u043e\u0441\u0442\u044c (0-100%)')),
                ('frp', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='\u043c\u043e\u0449\u043d\u043e\u0441\u0442\u044c \u043f\u043e\u0436\u0430\u0440\u0430')),
                ('brightness21', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='\u0442\u0435\u043c\u043f\u0435\u0440\u0430\u0442\u0443\u0440\u0430 \u043f\u043e \u043a\u0430\u043d\u0430\u043b\u0443 21/22 (\u0432 \u041a\u0435\u043b\u044c\u0432\u0438\u043d\u0430\u0445)')),
                ('brightness31', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='\u0442\u0435\u043c\u043f\u0435\u0440\u0430\u0442\u0443\u0440\u0430 \u043f\u043e \u043a\u0430\u043d\u0430\u043b\u0443 31 (\u0432 \u041a\u0435\u043b\u044c\u0432\u0438\u043d\u0430\u0445)')),
                ('scan', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='\u0440\u0430\u0437\u043c\u0435\u0440 \u043f\u0438\u043a\u0441\u0435\u043b\u0430 \u0432 \u043d\u0430\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0438 \u0441\u043a\u0430\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('track', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='\u0440\u0430\u0437\u043c\u0435\u0440 \u043f\u0438\u043a\u0441\u0435\u043b\u0430 \u0432 \u043d\u0430\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0438 \u0442\u0440\u0430\u0435\u043a\u0442\u043e\u0440\u0438\u0438')),
                ('version', models.CharField(max_length=6, verbose_name='\u0432\u0435\u0440\u0441\u0438\u044f')),
                ('night', models.BooleanField(default=0, verbose_name='\u041f\u0440\u0438\u0437\u043d\u0430\u043a \u043d\u043e\u0447\u043d\u043e\u0433\u043e \u0441\u043d\u0438\u043c\u043a\u0430')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'fire',
                'verbose_name': 'MODIS \u0434\u0430\u043d\u043d\u044b\u0435 \u043e \u043f\u043e\u0436\u0430\u0440\u0435',
                'verbose_name_plural': 'MODIS \u0434\u0430\u043d\u043d\u044b\u0435 \u043e \u043f\u043e\u0436\u0430\u0440\u0430\u0445',
            },
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite', models.CharField(max_length=5, unique=True, verbose_name='\u0441\u043f\u0443\u0442\u043d\u0438\u043a')),
                ('short_satellite_name', models.CharField(max_length=1, unique=True, verbose_name='\u0441\u043f\u0443\u0442\u043d\u0438\u043a \u0441\u043e\u043a\u0440\u0430\u0449\u0435\u043d\u043d\u043e')),
            ],
            options={
                'db_table': 'satellite',
                'verbose_name': '\u0421\u043f\u0443\u0442\u043d\u0438\u043a',
                'verbose_name_plural': '\u0421\u043f\u0443\u0442\u043d\u0438\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='fire',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fires_app.Satellite'),
        ),
        migrations.AlterUniqueTogether(
            name='fire',
            unique_together=set([('geometry', 'date')]),
        ),
    ]
