# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires_app', '0003_auto_20170410_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='url_viirs',
            field=models.URLField(default=b'https://firms.modaps.eosdis.nasa.gov/active_fire/viirs/shapes/zips/VNP14IMGTDL_NRT_Global_24h.zip', verbose_name='URL MODIS'),
        ),
    ]
