# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires_app', '0004_siteconfiguration_url_viirs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireviirs',
            name='confidence',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='\u0434\u043e\u0441\u0442\u043e\u0432\u0435\u0440\u043d\u043e\u0441\u0442\u044c (0%, 50%, 100%)'),
        ),
        migrations.AlterField(
            model_name='fireviirs',
            name='date',
            field=models.DateTimeField(verbose_name='\u0434\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f (UTC) \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u0434\u0430\u043d\u043d\u044b\u0445 \u043e VIIRS'),
        ),
    ]

