# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-18 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires_app', '0005_auto_20200408_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='firemodis',
            name='time',
            field=models.TimeField(null=True, verbose_name='\u0434\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f (UTC) \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u0434\u0430\u043d\u043d\u044b\u0445 \u043e MODIS'),
        ),
        migrations.AddField(
            model_name='fireviirs',
            name='time',
            field=models.TimeField(null=True, verbose_name='\u0432\u0440\u0435\u043c\u044f (UTC) \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u0434\u0430\u043d\u043d\u044b\u0445 \u043e VIIRS'),
        ),
        migrations.AlterField(
            model_name='firemodis',
            name='date',
            field=models.DateField(null=True, verbose_name='\u0434\u0430\u0442\u0430 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u0434\u0430\u043d\u043d\u044b\u0445 \u043e MODIS'),
        ),
        migrations.AlterField(
            model_name='fireviirs',
            name='date',
            field=models.DateField(null=True, verbose_name='\u0434\u0430\u0442\u0430 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u0434\u0430\u043d\u043d\u044b\u0445 \u043e VIIRS'),
        ),
    ]
